### ISSUE TITLE
Request to publish

### ISSUE THREAD

**Issue by scottf** [iivanf/NatsKotlin#1]
@iivanf Would you please contact me? My Synadia email is in my github profile. I would like to get this listed on our Downloads page under Connectors and Utilities. https://nats.io/download/ but want your permission first.

Also, if you are interested, what would you think about writing a short blog post to add to our blog? https://nats.io/blog/
It doesn't have to be very long to explain a little bit about your code. it would just be a simple markdown doc, I will help you make a PR and get it submitted.

**Comment by iivanf** [comment]
@scottf  I sent you an email. Thank you
